# Generated by Django 2.2.19 on 2023-02-11 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id',
                 models.AutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID'
                    )
                 ),
                ('title', models.TextField(max_length=30, unique=True)),
                ('slug', models.SlugField()),
                ('description', models.TextField()),
            ],
        ),
    ]
